language: node_js
node_js:
- 0.10.25
before_install:
- npm install -g gulp
- npm install
script:
- gulp scss
sudo: false
deploy:
  provider: npm
  email:
    secure: klJ6ZfJBrRk/cvGfTiQW5/0qNOzZgsc1uBgMbTKS1xSyLKR5bQhvMceodt4+Je6UjYzHieX3rZCp8qvtdV/nkQgEYhTZWfcrhK248BsoN8A6aPR5tjhb3hshKvfW1f21wu9Z/kUnSmQ9fiB2KYiLlhewVp9ne3XXLUYo5isQ/BgdKXrjBDLfHa57CND+W4TGe3Z2rcG4vT/kHfs7eQky2eQjtkPZ8ov4HbW68kvxlR64ewYayoxqBilDzNDKD7+14xMw0p4MQBBDZ5f9oyz3rcnxRUuAgl/lRFW4Uv9L9tD7zFb2CFafMd4mDnMljPUf/An7zmoLUc9pVlw+3D3ZGoTsHaTBtWYpashYEmzKy8MOixR7TPCpbm3/K6UgttkONbD2f6XC+MMJl9CdgWtORcxHUE94XQnoaX9QTz/K4N3KFZSrwCB9ZCrw5vnauohQnBZRVEPq4luYte/q3ABVoU5kOzu05HuAQx6xQJu7xxPOgx3wmXnUOFsm/eGUaZtxZocD3rOC7nPwg97r6cWdwQoi8t96F/O6+1iPa2rIklQWOH0FE8RNdL8I0qaQKDVMNRcn3vdHajTBvxYFxjNK1zjLCyho58/YEydxcKGIJl0DdWN1rSlIwwWRxu/mWEhzispkfpdIz9D4N2YLH4OEFObMBvxw0uVg1LSp6ZmHfqk=
  on:
    tags: true
  api_key:
    secure: maz/OGQ0o5ycsBw6EOlE/rWOFRxAH+0Fhf7nNeNmV7Af/hyDQg75gD/kQyYbiJ9LjOBxPo4/whZgEV7Uqwyc6YCQmbfMVXioAuWix5RYK1QJDbsQ9goHxR4J2q6xzrCRGUH5Vc015gIJbeu8eVNZ5mUdrgP5EqegWbemRdCMFVgN9TvVWj4Ib0oASarxfXJVkfM+JVjHdCiF68jTQacAojHswE4nYBWZkre5XpwI4fQALriOzCyX51E2yCQBf2lWcc794uUEn2z9D2jACPy/KBXyoxZ4ERx43mCQ1T9Wb0auxzFl/xz47CLhj3cn80+O4YOPLtaij4I2TTg4m1dyQE/ALC3stMvbmNkmFs22O07gEN869do/e7hqmrdVTl5MddcA7eUsTEn0jQWEY/SHNl1/oxQdwsAFHxlN2Dbub6C7nPFNKKOor1Hpl1BVjVus3gtg/SIF+LhQy7nS5mqZBXdrE7MoYqymFv3y97wacV3a2N/9RxWkkhMbquumEDnBZkOFR19mqLNcSe/2x9G7oi/e1D6XAYeN5saYvuAlgPmZZz8+g7nOiH1D3lJjZF/ei9ZeAqV09GKhC1AKjC9RjjhifFDgDQxijxScPG2Jg+u3jxmKf7v46+NgoH4535wTyhBoBotZoaOkJ5cvfcVeHNSTKG1W1ag2tnJjPA79bx4=
