language: node_js
node_js:
- 0.10.25
before_install:
- npm install -g gulp
- npm install
script:
- gulp scss
sudo: false
deploy:
  provider: npm
  email: atran@appirio.com
  on:
    tags: true
  api_key:
    secure: vlaz21kpqKuk229DRXQq3cmDDcR9OIhfYZ0/7xjLePvJAQFHm8C+tkfKS5BbXob43n3mm5WFd2Cu/+/QhEso4s0NF1pUNNod1l6ra9l9K0F/rUDu5NzOjccWtN7TIKeo7henjhET3y9VtBjPgvjImfk/WYL98wONfM6+0ZmBZGYZJE++Qylwpu820rfrD+EYxC3uZpnQA0EijoGE9Lpxsj706QhPhUlJEbVSl8P9xvgeouyNCeQ/qMfFXr3uqqNkq0Pt52J4w6Lq2KZJsUTGxrSLdgaKY6TuuQTvAk3Fchw+Wbl8I8U1mc987aqm8qXcQu1GGJ3C5QzQ2y2TL7dIenLF7p33D5usF/MUD2d8Ri4LlY/0B3up0DLUZdEd9TqMYiJDuHwpOZjCpWJvRfNz3NaaQ+hjkWeU4s2Vfz0EdW5IOFsOKm/UFMlOKLCSzxW1CB6TOH0+alG83oWa/beCGIcTx1wA30EB0Y5nLnHhhqCuZO1Tngt5frx1yx1bzN/KfDx2FZ2bev4WTvUg9mBKdFwMbsk8uhztYQARsa+u9yAKPV83BtzEhkA9toV2iSLb8d/U3i7WTj3ogEyuY0B2ylJQhlB8DrhUn4jjZVnAKjRS8zkrR8oeQPIEmQGFxB041Leiy6OTIffP2YGYV72r6ow4+O7LH/L2t2O6Z5nkz80=
