language: node_js
node_js:
- 0.10.25
before_install:
- npm install -g gulp
- npm install
script:
- gulp scss
sudo: false
deploy:
  provider: npm
  email:
    secure: lrI8ea41BFJM38dmCt3fzFRtWeA7mU19EbODmVrwAYIfYS4KEWNiH4dij209baUNwP9BBjry7saGuIYDgSLTTfbMU9feGA57WEO9XN3FrTBacDJirZ9bTYbfe8mHBsrHpXQ6xlexYdKrUqn5/D/g2AyNju7Ds2YpyFjRfcy4BMvSgXNmgPTO2gy4ih4y9TRtVUoBmrj9jRSLsihf6fkw2kmE3CoOwCqGHtEF92R2qMFfgZMB2vG3p8oY4W7FGMzhMYYIPbCdGR8MOosU8zTIhZtXNgBIlv/A5ge2xkfKtt5tdi28iABo9jIDYytg0X9QN1ueTCre/mkRPl1u2WkNTkt3XwbLNhzy3SFsGeVNnYVd3XRLWJtF93+2HFtuN2OZdW90tvvw0JZFHJ/y5AhSs2LPuYGbbYzQWY5XMFC/ngTZHz1vr6MyPHAuvD0ocx8iN1KamjBkFK1VXQRb772Gu7nGJlA/uOd+byDZOShjp8/ALK/ZEsYt7qS2xz/r1l+pkad0Y62jOmGKtyzpTb8QGZZDyLP/YdYpwAS8YhMs1VOXK2pNIOAYMSr5PhxAoKVU1SAllo0eC9ec468lgTW0OhwyWfcdhZlwrQe1mMoKLk714F1pdkOKmzPGlIn67ICusKjlpuggHsDeIeL+U6OHjA6JkkOieS4rhNmX0gF1NWY=
  on:
    tags: true
  api_key:
    secure: eazG5MUxnmkM/p9tvDLIjF2Zz6Cq4Mh9FpFC/eEAWhVhKspCNzRtE8g3DIhyFy6vZHjn+iJ/tmw2imp++eKFuz/SMBX+pBC1KpX+ksEyEzMRemLCi6b6xloZ/Pkkl7Ou9A+x+NNxctLyzUHnsDBUohAtXImG5ZwsYySp4NZFAUVIT8Om5spzrhiwmrnF9sUIs0LhFqJghOfTnWsRMe9dMPKQXtNqf+mJotpAzOPlkDSHZMv/RiAcziyXVW6uA/GZu2RF0iLYHgNLhdi8oWTiOUj0TqcSh3YTvBnWrcMgQ1uFvRpjpnIiK0i44rq/XVgSc5hIIfrporijL/PvDTvjZ4T+EuDXXIo1neRjQNMMn9PdIFYsxE39D4oKnY0a55l5n2PK++op5Tav9xwP9nl0i7dJ1QwprfDQEBoQxKDhL1wM8SNW994dpP7da5FLPOrkf1r6M5GQnQFn2ccxZsOJmoMllIdzKKq9T7CWwrejVyI+0FajVdbgVFkX9KC/62yovDoKfL3TC5eDc9+V/nWrXdbTCVUDlp25Pj+5pUzZrMazsL9npqDhGxmWT/RgKIJyQPW9Asq4YYY+8XeNgsR6zUwjZR6AbtjHFILmM3R7vv6Dv1B7JmMf17ng5CaeokeBz/DgQ/V0PEkW8+7GGK9dJVf+ffK0ZhaSULeCCFmjefU=
