language: node_js
node_js:
- 0.10.25
before_install:
- npm install -g npm
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp scss
sudo: false
deploy:
- provider: s3
  cache_control: max-age=31536000
  detect_encoding: true
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: styles.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: VOMeqM3o1zUh4kXBA/qLavHJSbmR3gQ1WIo3cr9m2/euYoFTeHJKnz9h1TnJm2zV3AgTDRFOBGTiHeSE1MNm3FO6Sd+yRNWbAa7DVkhE2axoWyU65gJ3JlyXSLsWI3IT/BIIRIKQ9ck7QCHxnvi1H6yA5Ubk/Ks+686FowdgF3IdahJxbSZv2EQAnoINfYT7LAgx8HpFJxTRIqgjHaANTznweBgKig5NBkovraRb0CcWRJO9t7fOQrsqv4D+uJSZXuyaSbiP8VH/EHxQ8RWPk9z1gElBVhuT2NBht0/V3MCUCn937t7DynwkvKbqiecwKHOVlVh5sBtr6itRq5LBb83olX4UjPeuOW3zqRs/CSedjupN0sI6f2vW3jeoaw5THrExluW7mQEOWX2he+buRzyiw1M1PEDhD8lMgA9SRLnw8RTJwDgzYCh/ff9IApWLzqb0ZBXEyz5RX1s7kv8qVtasAK9V9yarOqWF78Ge7GYWJxkQV7grYXsRyRIeH2kooifhkVDY9SDsDt7mLhM/4WdJ8UcSkRLGYoFPX2VKAhwxAsaWkfOiDL7/aRyCUh1iDTjz/YIo3u63WYr1c/B/kFAgO8mr5NdhBdx1/lVjmBRSBfrhx783WwZFFF3xbgPm3EkHmi6//7BraiR2f3Y7BCML8D+5RbhiwqCSmR0ZfE8=
  - secure: LBxIN+5XS8juyo1HtgmJpCoo/TvBgrvtlj3QhX8XXIE+80u8qbQ54PN97veGoBNiSX3JXZqSZ0+4T35PskS9Q/I8U8/OjsVnMVckf8NbR4DfZbiLtCkgQ9m/4IR8G246lAoeh9DpdBq56s8ChwCVIYrKtu9iJLR8EBQ6Cq8LXcsFgoo6SUgPFb36COKCL7JamZ8+uFAwbqckVzC55c6qvqZR2ogM0ZU4Uy+gwsU3+VJaPVA65h1cU5NFE7CbqxEt2CvcagzPHYa7yvptip6UT0ujn5gYFQ5TcHEGHp+Va7QwnhzVjNJIOHwIRolBSZIe2DG4d01MLaF4C/wY046WDlZo5PeDJt8+wrvGCXFmOq6KZTxNMAELhuZQF2SAJ0KNhL+fcGPksxTTMUUJZNbNMYgFjjFJ2aUt9kZe+grWkwhBdvmvmyS7WwEtoTXhTBNZJTBqzzxgduzMDbzRdu+O8mrFY7L4rAaIyVDkkON/0FipQzhjAQswh/zJ89PX+Z9wjvtvL5kuauagI2d5UVY0JxocTZhZacl3wLDx54DZvR0c3KSzm0LKrCG/GacydkjFaF0azxn06GeekV0ZFGPjPEENrVjRIvuk0LAxavUAsUM+51fpMVsQhQGjXJKeQ2M9QvDK7HPX6XC5Ccd4l45z0CXj6a6fs9YlXaAShZA9FCw=
  - secure: TpVS9CYRfJxAFAeR+/X20UeSxrdvkE9ZVJHcPW9WqlmHaISJmiaZfJ5uuCRk9VZDE1Mh0b8uxTuWCtO+vK8mdSU2IzkNF7uP1L6K00QogLJUlgCI/x9JNqYxqmd53gNUQ7jJd77VGH5JRWql4MAGb8sjUzSCq0POpEKKA6tzUsVDDSBq2TcDSGA1mvntq2GKXCJqLNU456d9JZmqm2PlpLJGQ/3JOKsS3IL3SXRKSkxB5P+EAQ3BrQtQHL5zhcA2705UmUY/DWUv4JwiPFvT6AsOBHUlMnUbeAy8jCQ3/tJlM1sZ9Sne6AwVzmiTHw74K72WFtu6/TpdH35Zxc8q4Gx2lMWCKE1UaMH7qvacXL0OKSMgkOLagCnN6egALVHxhw+xutHN53IwEX0F3GjROVnS+aTOtA1euBW0GFzxZ3ndZKQohYQuBYDtiJQeUkhiJ6yr4Evjt8fXgocWYRvHWB42EZA8h3o/EsIPfN9WhcJPVK8nju3Syltdo4MtPWc7seiXwO00ToH7y46jTt+4vo77lexUvCtvJHo2enwOZTUSJOOBhWdSzaWCC/Zm9HFqcdiTAAZiIcQYdU72o4L8z8bWGGgQtBLZpy5l29JYRyiY8cTVjR4IjudxGQVlJmva9pO34hvY7pxE+TGsUXpBL3//pa8Q+8wC0ONDfcrXvjw=
  - secure: lYKLz1A4i6TF48HuPVMInIfNEozURIUEztSJxHbMvAAzlaE6fpO6dq8hLvr0CJHHV9WD1M/vU0ZZN1vQMr4SYrNDTH4L0LXOmjnjrt1eZXI503UxmCAof0deMfA94qj+0hRr20+9b7X2AzUdtdWR8ah/0mNqApM/FxnkHP9WjcYj/Sqx4h3IBTqCTrfrLegaiXCTHnfMqrXGxYFsqV8t0rU/8s2z1R0eETkJWKoDx8UVkxbex6YC0xLopdXF7Fb6xuU8r93mii3p/HfUwIinsXl7Y4B7aI3G+YbzdkYhH5qteUHUzbz0jyvE5y/zJpRbuOVIOu/hDCoq2awwjDgulZLO82Qiv6Ht7sWcuP9ENey0uB6347/aLVyYaiKS2EmORtF5kXtPdLCN7hj07X7QnigF+zgr5lWEFk9g+mlIkg5pcpP2QV3ivRvkwbGVMVWnifi1h3sgRU7tMYBakprka5+G4Mw4lprdTKwRiAxHcsF4OWi8PQSGaBh+SgXtDPZe4jn/3+ZPd3aq/S7yBcYhKvtNPEWkM/mF/8nfk3ThFR+EdM13NLDJspI6KChZlrPa61UkJZPPzmIvO4+ItH1YjNAOHFXtBzgz2AQKV9NQ0ABqOMM11sVELGtiURXETw3ZLNBIKe4H3s8JEJERuYjhZlJIcm8d9Y00EKL8Rwwxf2o=
