language: node_js
node_js:
- 0.10.25
before_install:
- npm install -g npm
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp scss
sudo: false
deploy:
- provider: s3
  cache_control: max-age=31536000
  detect_encoding: true
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: styles.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
env:
  global:
  - secure: VOMeqM3o1zUh4kXBA/qLavHJSbmR3gQ1WIo3cr9m2/euYoFTeHJKnz9h1TnJm2zV3AgTDRFOBGTiHeSE1MNm3FO6Sd+yRNWbAa7DVkhE2axoWyU65gJ3JlyXSLsWI3IT/BIIRIKQ9ck7QCHxnvi1H6yA5Ubk/Ks+686FowdgF3IdahJxbSZv2EQAnoINfYT7LAgx8HpFJxTRIqgjHaANTznweBgKig5NBkovraRb0CcWRJO9t7fOQrsqv4D+uJSZXuyaSbiP8VH/EHxQ8RWPk9z1gElBVhuT2NBht0/V3MCUCn937t7DynwkvKbqiecwKHOVlVh5sBtr6itRq5LBb83olX4UjPeuOW3zqRs/CSedjupN0sI6f2vW3jeoaw5THrExluW7mQEOWX2he+buRzyiw1M1PEDhD8lMgA9SRLnw8RTJwDgzYCh/ff9IApWLzqb0ZBXEyz5RX1s7kv8qVtasAK9V9yarOqWF78Ge7GYWJxkQV7grYXsRyRIeH2kooifhkVDY9SDsDt7mLhM/4WdJ8UcSkRLGYoFPX2VKAhwxAsaWkfOiDL7/aRyCUh1iDTjz/YIo3u63WYr1c/B/kFAgO8mr5NdhBdx1/lVjmBRSBfrhx783WwZFFF3xbgPm3EkHmi6//7BraiR2f3Y7BCML8D+5RbhiwqCSmR0ZfE8=
  - secure: LBxIN+5XS8juyo1HtgmJpCoo/TvBgrvtlj3QhX8XXIE+80u8qbQ54PN97veGoBNiSX3JXZqSZ0+4T35PskS9Q/I8U8/OjsVnMVckf8NbR4DfZbiLtCkgQ9m/4IR8G246lAoeh9DpdBq56s8ChwCVIYrKtu9iJLR8EBQ6Cq8LXcsFgoo6SUgPFb36COKCL7JamZ8+uFAwbqckVzC55c6qvqZR2ogM0ZU4Uy+gwsU3+VJaPVA65h1cU5NFE7CbqxEt2CvcagzPHYa7yvptip6UT0ujn5gYFQ5TcHEGHp+Va7QwnhzVjNJIOHwIRolBSZIe2DG4d01MLaF4C/wY046WDlZo5PeDJt8+wrvGCXFmOq6KZTxNMAELhuZQF2SAJ0KNhL+fcGPksxTTMUUJZNbNMYgFjjFJ2aUt9kZe+grWkwhBdvmvmyS7WwEtoTXhTBNZJTBqzzxgduzMDbzRdu+O8mrFY7L4rAaIyVDkkON/0FipQzhjAQswh/zJ89PX+Z9wjvtvL5kuauagI2d5UVY0JxocTZhZacl3wLDx54DZvR0c3KSzm0LKrCG/GacydkjFaF0azxn06GeekV0ZFGPjPEENrVjRIvuk0LAxavUAsUM+51fpMVsQhQGjXJKeQ2M9QvDK7HPX6XC5Ccd4l45z0CXj6a6fs9YlXaAShZA9FCw=
