language: node_js
node_js:
- 0.10.25
before_install:
- npm install -g gulp
- npm install
script:
- gulp scss
sudo: false
deploy:
  provider: npm
  email:
    secure: klJ6ZfJBrRk/cvGfTiQW5/0qNOzZgsc1uBgMbTKS1xSyLKR5bQhvMceodt4+Je6UjYzHieX3rZCp8qvtdV/nkQgEYhTZWfcrhK248BsoN8A6aPR5tjhb3hshKvfW1f21wu9Z/kUnSmQ9fiB2KYiLlhewVp9ne3XXLUYo5isQ/BgdKXrjBDLfHa57CND+W4TGe3Z2rcG4vT/kHfs7eQky2eQjtkPZ8ov4HbW68kvxlR64ewYayoxqBilDzNDKD7+14xMw0p4MQBBDZ5f9oyz3rcnxRUuAgl/lRFW4Uv9L9tD7zFb2CFafMd4mDnMljPUf/An7zmoLUc9pVlw+3D3ZGoTsHaTBtWYpashYEmzKy8MOixR7TPCpbm3/K6UgttkONbD2f6XC+MMJl9CdgWtORcxHUE94XQnoaX9QTz/K4N3KFZSrwCB9ZCrw5vnauohQnBZRVEPq4luYte/q3ABVoU5kOzu05HuAQx6xQJu7xxPOgx3wmXnUOFsm/eGUaZtxZocD3rOC7nPwg97r6cWdwQoi8t96F/O6+1iPa2rIklQWOH0FE8RNdL8I0qaQKDVMNRcn3vdHajTBvxYFxjNK1zjLCyho58/YEydxcKGIJl0DdWN1rSlIwwWRxu/mWEhzispkfpdIz9D4N2YLH4OEFObMBvxw0uVg1LSp6ZmHfqk=
  on:
    tags: true
  api_key:
    secure: HPZKzdMZ6lkpi9ao8S7nDJ3lMvvnrk8ns8qFzBxluPfaUCFTR5+NkU0ahliKFbGgiYHir2Qf3L8YqnUX6pMBIEIfwT+wwFIi2BFNZ5+52YVbuIc39UxEigSc0nZ6B9D5i3AdN3Dkk/yHhMDR1RLot7ob1vwX/XCDTmGqzKUzFRPDka6n2Pj4a11qYT2A5LTSSy5o0tm+udGo64pXd9J5yJrEovlOA2crHWlXop0ieJi7ojwskE9ylNbbdNQBF3731YGT8x6egGPreQo25V1DuEVuiDKGHcJyvBUYRR0r7K0Bl0Mi3LSrKcTUMGpQKo7EJG8JncHL3vZ4LPEBoYXs2eLOvg/6M6Z1brOFhGt41YGSdySde/+gCH+T/31jOd7HSDdnqNtUAhuZVsTmFZ0P0WtOfQuW0qDghIU+DWF/cg42GBAr4A1ffXGgjLK6yaYsbxqSQuVJ1MKakaGxv/japYCEATm4uPWPRXLxf6iQm3jsqkkeruKp/81KdyuFiX/7SI24/pLCWxdeuuKmuU2n7MGttE8NEvzf4L1gCGDXPec+bvnQaYvtY7xYCIf3KPdUHSPb77zIemM0undR43C5NIRzdnc2Ocmfyq0LRhe6LkKSdceuh662sXhn0DZ/qDN5wAB78hJfXZj4KeXgZb42VnK0z63Ls9seWUIotD1Q9jQ=
